# Generated by Django 3.2.9 on 2021-11-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_photos_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='image',
        ),
        migrations.AddField(
            model_name='photos',
            name='file',
            field=models.FileField(blank=True, upload_to='file'),
        ),
    ]
